CREATE DATABASE vendas_sucos;

USE vendas_sucos;

CREATE TABLE produtos
(
CODIGO VARCHAR(10) NOT NULL,
DESCRITOR VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR(50) NULL,
PRECO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO)
);

CREATE TABLE vendedores
(
MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NULL,
BAIRRO VARCHAR(50) NULL,
COMISSAO FLOAT NULL,
DATA_ADMISSAO DATE NULL,
FERIAS BIT(1) NULL,
PRIMARY KEY (MATRICULA)
);

CREATE TABLE clientes (
  CPF varchar(11) NOT NULL,
  NOME varchar(100) DEFAULT NULL,
  ENDERECO varchar(150) DEFAULT NULL,
  BAIRRO varchar(50) DEFAULT NULL,
  CIDADE varchar(50) DEFAULT NULL,
  ESTADO varchar(45) DEFAULT NULL,
  CEP varchar(8) DEFAULT NULL,
  DATA_NASCIMENTO date DEFAULT NULL,
  IDADE int(11) DEFAULT NULL,
  SEXO varchar(1) DEFAULT NULL,
  LIMITE_CREDITO float DEFAULT NULL,
  VOLUME_COMPRA float DEFAULT NULL,
  PRIMEIRA_COMPRA bit(1) DEFAULT NULL,
  PRIMARY KEY (CPF)
);

CREATE TABLE `vendas_sucos`.`notas` (
  `NUMERO` VARCHAR(5) NOT NULL,
  `DATA_VENDA` DATE NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `MATRICULA` VARCHAR(5) NOT NULL,
  `IMPOSTO` FLOAT NULL,
  PRIMARY KEY (`NUMERO`));
  
  CREATE TABLE `vendas_sucos`.`itens_notas` (
  `NUMERO` VARCHAR(5) NOT NULL,
  `CODIGO` VARCHAR(10) NOT NULL,
  `QUANTIDADE` INT(11) NULL,
  `PRECO` FLOAT NULL,
  PRIMARY KEY (`NUMERO`, `CODIGO`));
  
  CREATE TABLE tabela_de_vendas
  (
  NUMERO VARCHAR(5) NOT NULL,
  DATA_VENDA DATE NULL,
  CPF VARCHAR(11) NOT NULL,
  MATRICULA VARCHAR (5) NOT NULL,
  IMPOSTO FLOAT NULL,
  PRIMARY KEY(NUMERO)
  );
  
  CREATE TABLE itens_notas (
  NUMERO VARCHAR(5) NOT NULL,
  CODIGO VARCHAR(10) NOT NULL,
  QUANTIDADE INT,
  PREÇO FLOAT,
  PRIMARY KEY (NUMERO,CODIGO)
  );