USE vendas_sucos;

 ALTER TABLE tabela_de_vendas ADD CONSTRAINT FK_CLIENTES FOREIGN KEY (CPF) REFERENCES clientes (CPF);
 
 ALTER TABLE tabela_de_vendas ADD CONSTRAINT FK_MATRICULA FOREIGN KEY (MATRICULA) REFERENCES vendedores (MATRICULA);
 
 ALTER TABLE itens_notas ADD CONSTRAINT FK_NOTAS FOREIGN KEY (NUMERO) REFERENCES NOTAS (NUMERO);

 ALTER TABLE itens_notas ADD CONSTRAINT FK_PRODUTOS FOREIGN KEY (CODIGO) REFERENCES PRODUTOS (CODIGO);
 
 